FROM node:latest 

RUN apt update 
# RUN apt install -y g++ make qt5-default

# WORKDIR /app

# COPY . .

# RUN qmake netcode-cpp.pro
# RUN make

# FROM debian:buster-slim AS runtime-stage

# RUN apt update && apt install -y --no-install-recommends libqt5core5a libqt5network5 libqt5widgets5

# WORKDIR /app

# COPY --from=build-stage /app/netcode-cpp /app/

# EXPOSE 12345/tcp 12346/udp

# CMD ["./netcode-cpp"]
